=== myphpframework/mpf-core/dtd/database.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
   TODO: DTD is apparently not valid, find out why...

   An example how to use this DTD from your XML document:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE databases SYSTEM "http://myphpframework.com/dtd/database.dtd" >
<databases>
   <server engine="MYSQL">
       <host>localhost</host>
       <port>3306</port>
       <access type="rw" for="1">
           <database>newbiverse</database>
           <login>root</login>
           <password>1111</password>
       </access>
   </server>
   <server engine="MYSQL">
       <host>localhost</host>
       <port>3306</port>
       <access type="r" for="2">
           <database>newbiverse</database>
           <login>root</login>
           <password>1111</password>
       </access>
       <access type="w" for="2">
           <database>newbiverse</database>
           <login>root</login>
           <password>1111</password>
       </access>
   </server>
</databases>


-->

<!ELEMENT databases (server)*>
<!ELEMENT server (host,port,access)>
<!ATTLIST server engine (MySQL|MySQLi|SQLite|Oracle|MSSQL|PostgreSQL) "MySQLi" #REQUIRED>
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT access (database,login,password)>
<!ATTLIST access
    type (r|w|rw) "rw" #REQUIRED
    access for CDATA #REQUIRED>
<!ELEMENT database (#PCDATA)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== myphpframework/mpf-core/UnitTest/config/dbTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE databases SYSTEM "http://myphpframework.com/dtd/database.dtd" >
<databases>
   <server engine="MySQLi">
       <host>localhost</host>
       <port>3306</port>
       <access type="rw" for="1">
           <database>test</database>
           <login>test</login>
           <password>test</password>
       </access>
   </server>
   <server engine="PostgreSQL">
       <host>localhost</host>
       <port>5432</port>
       <access type="rw" for="2">
           <database>test</database>
           <login>test</login>
           <password>test</password>
       </access>
   </server>
   <server engine="SQLite">
       <host>/var/www/sqliteDb/</host>
       <port>010</port>
       <access type="rw" for="2">
           <database>test</database>
           <login>test</login>
           <password>test</password>
       </access>
   </server>
</databases>

=== myphpframework/mpf-core/UnitTest/config/dbTestUnsupportedDbType.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "http://myphpframework.com/dtd/database.dtd" >
<databases>
   <server engine="BOBISNOTANENGINE">
       <host>localhost</host>
       <port>3306</port>
       <access type="rw" for="1">
           <database>newbiverse</database>
           <login>root</login>
           <password>124357</password>
       </access>
   </server>
   <server engine="BOBISNOTANENGINE">
       <host>localhost</host>
       <port>3306</port>
       <access type="r" for="2">
           <database>newbiverse</database>
           <login>root</login>
           <password>124357</password>
       </access>
       <access type="w" for="1">
           <database>newbiverse</database>
           <login>root</login>
           <password>124357</password>
       </access>
   </server>
</databases>

=== myphpframework/mpf-core/scripts/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE databases SYSTEM "http://myphpframework.com/dtd/database.dtd" >
<databases>
   <server engine="">
       <host />
       <port />
       <access type="rw">
           <database />
           <login />
           <password />
       </access>
   </server>
</databases>
