=== myphpframework/mpf-core/dtd/i18n.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>
    <!DOCTYPE lang SYSTEM "http://myphpframework.com/dtd/i18n.dtd">
    <i18n>
       <country code="CA">
           <text id="someid1">somevalue1</text>
           <text id="someid2">somevalue2</text>
       </country>
    </i18n>
-->

<!ELEMENT i18n (country)*>
<!ELEMENT country (text)*>
<!ATTLIST country code CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ATTLIST text id CDATA #IMPLIED>

=== myphpframework/mpf-core/i18n/fr/mpf_exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "http://myphpframework.com/dtd/i18n.dtd" >
<i18n>
    <country code="CA">
        <text id="dbDatabaseNotBootstrapped">L'envrionement pour la base donnée n'a pas été bootstrappé, vous pouvez le faire de la manière suivante: ENV::bootstrap(ENV::DATABASE);</text>
        <text id="dbInvalidHashAlgo">L'algorithme "@algo@" est pas pris en charge, s'il vous plaît assurez-vous que ca soit un de ceux-ci: "@algoList@"</text>
        <text id="dbInvalidFieldValue">Le type de valeur pour le champ "@fieldName@" du modèle "@model@" est erronée.</text>
        <text id="dbInvalidFieldType">Le type pour le champ "@fieldName@" du modèle "@model@" erroné, doit être un int, float, string ou null.</text>
        <text id="dbInvalidFieldLength">Le champ "@fieldName@" du modèle "@model@" a une longueur supérieure à celle spécifiée dans le modèle.</text>
        <text id="dbFieldNotNull">Le champ "@fieldName@" pour le modèle "@model@" ne supporte pas une valeur null.</text>
        <text id="dbFieldReadonly">Le champ "@fieldName@" pour le modèle "@model@" est défini comme en lecture seule par le modèle, donc vous ne pouvez pas le modifier.</text>
        <text id="dbInvalidDatabaseName">Nom de base de données invalide "@name@".</text>
        <text id="dbInvalidFieldName">Le nom de champ "@fieldName@" est invalide pour le modèle "@model@".</text>
        <text id="dbInvalidResultResourceType">Le type de resource est invalid, attendu "@expected@" reçu "@actual@".</text>
        <text id="dbInvalidConnectionType">Le type de connection est invalide, attendu "@expected@" reçu "@actual@".</text>
        <text id="dbInvalidQuery">La requête "@query@" n'a pas pu exécuter correctement, voir erreur: @error@.</text>
        <text id="dbConnectInfoNotFound">Les informations de connexion pour la base de données @name@ du type @dbType@ avec l'accès "@accessType@" n'a pas pu être trouvé.</text>
        <text id="dbInvalidAccessType">Le type d'accès "@accessType@" sont invalide.</text>
        <text id="dbInvalidConfig">Les configs de la base de donne "@fileame@" sont invalides, certains informations sont manquant.</text>
        <text id="dbUnsupportType">Le type "@type@" n'est pas supporté pour le moment.</text>
        <text id="dbDuplicateEntry">Il y a déjà une entrée avec la valeur "@value@" pour la clé "@key@" dans `@database@`.@table@.</text>
        <text id="dbModelTooManyPrimaryKeys">Le modèle doit avoir juste une clé primaire pour que le système de statut fonctionne correctement.</text>
        <text id="dbModelNoManyPrimaryKeys">Le modèle doit avoir au moin une clé primaire pour fonctionner correctement.</text>

        <text id="dbModelMissingStatuses">Le modèle a aucun statuts</text>
        <text id="dbModelMissingPhpDoc">Le modèle "@modelName@" requiert la phpdoc "@@phpdoc@" pour fonctionne correctement.</text>

        <text id="fileNotWritable">Le fichier "@filename@" n'est pas accessible en écriture.</text>
        <text id="folderNotWritable">Le dossier "@foldername@" n'est pas accessible en écriture.</text>

        <text id="textFileNotFound">Le fichier de texte "@filename@" n'a pu être trouvé dans: @paths@</text>
        <text id="textIdNotFound">L'id de texte "@id@" n'a pu être trouvé. IDs disponible: @availableIds@</text>

        <text id="bootstrapTypeNotSupported">Le type de boostrap "@type@" n'est pas supporté en se moment.</text>
        <text id="configUnknownEnvironment">Le nom d'environnement "@mpf_env@" est inconnue, soyez sur qu'il existe dans vos fichiers ini.</text>
        <text id="configOverlapping">La config "@config1@" rentre en conflit avec une autre.</text>
        <text id="bootstrapUnsupportedType">Le type d'environement "@type@" est inconnue.</text>

        <text id="serviceInvalidRequestMethod">La méthode "@method@" est invalide pour cette requête.</text>
        <text id="serviceInvalidRequestAction">L'action "@action@" est invalide pour cette requête.</text>
        <text id="serviceMissingRequestFields">La requête a certain champs manquand: "@fields@".</text>
        <text id="serviceUserAlreadyExists">Il y a déjà un compte avec cette utilisateur "@username@".</text>
        <text id="serviceUserNotApproved">Votre compte n'a pas encore été apprové.</text>
        <text id="serviceInvalidCredentials">Les informations d'accès sont invalide</text>
        <text id="serviceUserSuccessfulLogin">L'utilisateur (#@id@) @username@ a été logé avec succès.</text>
    </country>
</i18n>

=== myphpframework/mpf-core/i18n/fr/mpf_validations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "http://myphpframework.com/dtd/i18n.dtd" >
<i18n>
    <country code="CA">
        <text id="required">Ce champ est obligatoire.</text>
        <text id="alphanumeric">Must only contain alphanumeric characters</text>
        <text id="name">Le nom doit contenir des caractères alphabétique uniquement.</text>
        <text id="numeric">Ce champ doit contenir uniquement des chiffres.</text>
        <text id="passwordConfirm">La confirmation du mot de passe est invalide.</text>
        <text id="password">Le mot de passe doit contenir un minimum de 8 caractères.</text>
        <text id="email">Le courriel entré est invalide.</text>
        <text id="phone">Le numéro de téléphone entré est invalide.</text>
        <text id="country">Le pays indiqué est invalide.</text>
        <text id="state">La province sélectionnée ne correspond pas au pays.</text>
        <text id="creditCard">Numéro de carte de crédit invalide.</text>
        <text id="unexpected">Une erreur inattendue s'est produite.</text>
    </country>
</i18n>

=== myphpframework/mpf-core/UnitTest/i18n/en/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "http://myphpframework.com/dtd/i18n.dtd" >
<i18n>
    <country code="CA">
        <text id="test2">test value 2</text>
        <text id="test1">test value 1</text>
        <text id="testReplace">test the @name@ plz!</text>
        <text id="bbcodeTest">test the [b]name[/b] plz!</text>
        <text id="bbcodeTestDate">this is an [date]982342348[/date] date...</text>
        <text id="bbcodeTestDiv">this is an [div class="bob"]hullo[/div] div...</text>
        <text id="bbcodeTestInception">this is an [div class="bob"]hm or[span class="inception"]hullo[/span]test[/div] div...</text>
    </country>
</i18n>

=== myphpframework/mpf-core/i18n/en/mpf_exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "http://myphpframework.com/dtd/i18n.dtd" >
<i18n>
    <country code="CA">
        <text id="dbDatabaseNotBootstrapped">Database environment not bootstrapped, please do so with ENV::bootstrap(ENV::DATABASE);</text>
        <text id="dbInvalidHashAlgo">The algorithm "@algo@" is not supported, please make sure its one of these: "@algoList@"</text>
        <text id="dbInvalidFieldValue">The field "@fieldName@" for model "@model@" is of wrong value type.</text>
        <text id="dbInvalidFieldType">The field "@fieldName@" for model "@model@" is of wrong type, must be int,float,string or null.</text>
        <text id="dbInvalidFieldLength">The field "@fieldName@" for model "@model@" has a greater length than specified in the model.</text>
        <text id="dbFieldNotNull">The field "@fieldName@" for model "@model@" does not support null value.</text>
        <text id="dbFieldReadonly">The field "@fieldName@" for model "@model@" is defined as readonly by the model, hence you cannot modify it.</text>
        <text id="dbInvalidDatabaseName">Invalid database name "@name@". Forgot your config/dbs/default.xml?</text>
        <text id="dbInvalidFieldName">Invalid field name "@fieldName@" for model "@model@".</text>
        <text id="dbInvalidResultResourceType">Invalid result resource type, expected "@expected@" but got "@actual@".</text>
        <text id="dbInvalidConnectionType">Invalid connection type, expected "@expected@" but got "@actual@".</text>
        <text id="dbInvalidQuery">The query "@query@" failed to execute properly, see error: @error@</text>
        <text id="dbConnectInfoNotFound">The connection information for the database @name@ of the type @dbType@ with the access "@accessType@" could not be found.</text>
        <text id="dbInvalidAccessType">The database access type "@accessType@" is not valid.</text>
        <text id="dbInvalidConfig">The database config "@filename@" is invalid, some information are missing.</text>
        <text id="dbUnsupportType">The type "@type@" is not supported at this time.</text>
        <text id="dbDuplicateEntry">There is already an entry with value "@value@" for key "@key@" in `@database@`.@table@.</text>
        <text id="dbModelTooManyPrimaryKeys">The model must have 1 primary key only in order to work properly with status.</text>
        <text id="dbModelNoManyPrimaryKeys">The model must have 1 primary key atleast to work properly.</text>

        <text id="dbModelMissingStatuses">The model has no statuses</text>
        <text id="dbModelMissingPhpDoc">The model "@modelName@" requires the phpdoc "@@phpdoc@" to work properly.</text>

        <text id="fileNotWritable">The file "@filename@" is not writable!</text>
        <text id="folderNotWritable">The folder "@foldername@" is not writable!</text>

        <text id="textFileNotFound">The text file "@filename@" could not be found in: @paths@</text>
        <text id="textIdNotFound">The text id "@id@" was not found. Available IDs are: @availableIds@</text>

        <text id="bootstrapTypeNotSupported">The bootstrap type "@type@" is unsupported at this time.</text>
        <text id="configUnknownEnvironment">Unknown environment name "@mpf_env@", make sure it exists in your ini files</text>
        <text id="configOverlapping">The Config "@config1@" overlaps with another config.</text>
        <text id="bootstrapUnsupportedType">Unknown environment type "@type@".</text>

        <text id="serviceInvalidRequestMethod">Invalid request method "@method@"</text>
        <text id="serviceInvalidRequestAction">Invalid request action "@action@"</text>
        <text id="serviceMissingRequestFields">The request is missing the following fields: "@fields@"</text>
        <text id="serviceUserAlreadyExists">There is already an account with the username "@username@"</text>
        <text id="serviceUserNotApproved">Your account has not been approved yet</text>
        <text id="serviceInvalidCredentials">Invalid credentials</text>
        <text id="serviceUserSuccessfulLogin">User (#@id@) @username@ successfully logged in</text>
        <text id="serviceJsonParser">Could not parse json, returned error: @errorNumber@</text>
    </country>
</i18n>

=== myphpframework/mpf-core/i18n/en/mpf_validations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "http://myphpframework.com/dtd/i18n.dtd" >
<i18n>
    <country code="CA">
        <text id="required">This field is mandatory.</text>
        <text id="alphanumeric">Must only contain alphanumeric characters</text>
        <text id="name">Name must contain alphabetical characters only.</text>
        <text id="numeric">This field must only contain numbers.</text>
        <text id="passwordConfirm">Password confirmation mismatch.</text>
        <text id="password">The password must contain a minimum of 8 characters.</text>
        <text id="email">The email entered is invalid.</text>
        <text id="phone">The phone number entered is invalid.</text>
        <text id="country">The selected country is invalid.</text>
        <text id="state">The selected state does does not concord with the country.</text>
        <text id="creditCard">Invalid credit card number.</text>
        <text id="unexpected">An unexpected error occurred.</text>

        <text id="ajaxFormError404">The action of the form does not exist!</text>
    </country>
</i18n>
