=== myphpframework/mpf-core/dtd/language.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>
    <!DOCTYPE config SYSTEM "http://myphpframework.com/dtd/language.dtd">
    <languages>
        <language>
            <abrv2>fr</abrv2>
            <abrv3>fra</abrv3>
            <native>Français</native>
        </language>
        <language>
            <abrv2>en</abrv2>
            <abrv3>eng</abrv3>
            <native>English</native>
        </language>
        <language>
            <abrv2>es</abrv2>
            <abrv3>spa</abrv3>
            <native>Español</native>
        </language>
    </languages>

-->

<!ELEMENT languages (language)*>
<!ELEMENT language (native|abrv3|abrv2)*>
<!ELEMENT abrv2 (#PCDATA)>
<!ELEMENT abrv3 (#PCDATA)>
<!ELEMENT native (#PCDATA)>

=== myphpframework/mpf-core/i18n/languages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languages SYSTEM "http://myphpframework.com/dtd/language.dtd" >
<languages>
    <language>
        <abrv2>fr</abrv2>
        <abrv3>fra</abrv3>
        <native>Français</native>
    </language>
    <language>
        <abrv2>en</abrv2>
        <abrv3>eng</abrv3>
        <native>English</native>
    </language>
    <language>
        <abrv2>es</abrv2>
        <abrv3>spa</abrv3>
        <native>Español</native>
    </language>
</languages>
