=== myphpframework/mpf-core/xsd/database.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema targetNamespace="http://myphpframework.self/xsd"
    xmlns="http://myphpframework.self/xsd database.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name" />
                <xs:element type="xs:string" name="engine">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="MySQLi" />
                            <xs:enumeration value="PostgreSQL" />
                            <xs:enumeration value="SQLite" />
                            <xs:enumeration value="Oracle" />
                            <xs:enumeration value="MSSQL" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="server" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="host" />
                            <xs:element type="xs:short" name="port" />
                            <xs:element name="access" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="username" />
                                        <xs:element type="xs:string" name="password" />
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="type" use="optional">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="r" />
                                                <xs:enumeration value="rw" />
                                                <xs:enumeration value="w" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== myphpframework/mpf-core/UnitTest/config/dbs/dbTestUnsupportedDbType.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://myphpframework.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myphpframework.com/xsd/ database.xsd">
   <name>test1</name>
   <engine>BOBISNOTANENGINE</engine>
   <server>
       <host>localhost</host>
       <port>3306</port>
       <access type="rw">
           <login>root</login>
           <password>124357</password>
       </access>
   </server>
   <server>
       <host>localhost</host>
       <port>3306</port>
       <access type="r">
           <login>root</login>
           <password>124357</password>
       </access>
       <access type="w">
           <login>root</login>
           <password>124357</password>
       </access>
   </server>
</database>

=== myphpframework/mpf-core/UnitTest/config/dbs/dbTestMySQL.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://myphpframework.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myphpframework.com/xsd/ database.xsd">
   <name>test</name>
   <engine>MYSQLi</engine>
   <server>
       <host>localhost</host>
       <port>3306</port>
       <access type="rw">
           <login>test</login>
           <password>test</password>
       </access>
   </server>
</database>
